### PR TITLE
docs(api): add workaround for jsdoc bug

### PR DESCRIPTION
**Pull request by varl**
JSDoc has a bug where if a named import is the last statement before the
doc comment, then it fails to pick up the doc comment.

Any valid statement between the named import and the doc comment works
around the problem, such as `;` or `''`. Our code style rewrites a `''`
statement as `;('')`, and that is the shortest non-functional workaround
I have found to work around the problem.

Refs https://github.com/jsdoc/jsdoc/issues/1718
Refs https://github.com/jsdoc/jsdoc/issues/1706

Compare the result (broken on the left, correct on the right):

2019-12-13-165002_2019x1791_scrot

It also had the result that most of the modules were dropped, and the PropTypes rendered without their owner:

2019-12-13-165110_2427x2094_scrot

### CODE REVIEW

**Comment by amcgee** [comment]
Naive question - would a non-JSDoc comment work?

**Comment by varl** [comment]
> Naive question - would a non-JSDoc comment work?

Sadly, no.

With a normal comment the first AST node that JSDoc identifies is:

2019-12-13-174543_1297x808_scrot

With the `;('')` the first AST node is:

2019-12-13-174500_1909x1141_scrot

Which is what we expect. :thinking:

**Comment by varl** [comment]
> Naive question - would a non-JSDoc comment work?

Sadly, no.

With a normal comment the first AST node that JSDoc identifies is:

2019-12-13-174543_1297x808_scrot

With the `;('')` the first AST node is:

2019-12-13-174500_1909x1141_scrot

Which is what we expect. :thinking:

**Comment by varl** [comment]
> Naive question - would a non-JSDoc comment work?

Sadly, no.

With a normal comment the first AST node that JSDoc identifies is:

2019-12-13-174543_1297x808_scrot

With the `;('')` the first AST node is:

2019-12-13-174500_1909x1141_scrot

Which is what we expect. :thinking:

**Comment by amcgee** [comment]
@varl :-( OK

**Pull request merged**
