### PR TITLE
feat: extract centered content from screen cover

### PR DESCRIPTION
**Pull request by Mohammer5**
PR replacing #601

### CODE REVIEW

**Comment by ismay** [comment]
Why don't we call it AppCover? Would that be appropriate. My rationale is that the ScreenCover covers the screen, and the AppCover the area that's unique to the app (as in, anything but the headerbar).

**Comment by ismay** [comment]
Then the centering would not be that coupled to this component. It could be a feature though. But it seems that the base difference is _what_ it covers, and then secondary features might be how it renders its children (centered or not, etc.).

**Comment by Mohammer5** [comment]
> My rationale is that the ScreenCover covers the screen, and the AppCover the area that's unique to the app (as in, anything but the headerbar).

My idea was that this component could be used in any context for centering stuff inside a component (as long as the component is not positioned statically in css). If that's what this component will be used for, `AppCover` wouldn't be appropriate.

> Then the centering would not be that coupled to this component (by name at least). It could be a feature though

If we incorporate that feature officially, I'd name it more generic right from the start.
If we don't incorporate it, it's not really a feature, because that could change anytime, so using this "feature" could cause a change in this component to be an invisible breaking change (don't know if that's the correct terminology).

**Comment by Mohammer5** [comment]
> This component should also cover the use case in #576, so it needs additional props.

Ah, yes, good idea!

**Comment by Mohammer5** [comment]
> And it needs a better name.

See the description in the original PR:

> I don't like the name I came up with too much though: CoverCenter
> Maybe you guys have a better name?

**Comment by ismay** [comment]
> My idea was that this component could be used in any context for centering stuff inside a component (as long as the component is not positioned statically in css). If that's what this component will be used for, `AppCover` wouldn't be appropriate.

Ok, I thought that the intention of this component was to cover anything but the headerbar because of your comment in #601: `Imagine we want to cover the content of an app but not the headerbar. Currently the ScreenCover covers everything.`

So the intention of this component is just to center its children vertically and horizontally in the viewport?

**Comment by Mohammer5** [comment]
> So the intention of this component is just to center its children vertically and horizontally in the viewport?

Not the viewport but the component that it's rendered inside in.
The component is positioned absolutely currently, so it'd work with any container that's positioned either relatively or absolutely.

**Comment by ismay** [comment]
> > So the intention of this component is just to center its children vertically and horizontally in the viewport?
> 
> Not the viewport but the component that it's rendered inside in.
> The component is positioned absolutely currently, so it'd work with any container that's positioned either relatively or absolutely.

Ok. That seems very specific to me. Covering just the app seems like a useful component to me (since that's coupled to the headerbar height, which is difficult to know in an app). And a component for centering content in both directions seems useful (since that comes up from time to time). But a component for centering content in this manner seems very specific. Are there enough usecases for this that we need to export and maintain this as a separate component?

**Comment by varl** [comment]
> Ok. That seems very specific to me. Covering just the app seems like a useful component to me (since that's coupled to the headerbar height, which is difficult to know in an app).

We only know the Headerbar height in `ui-widgets` though, and `ui-core` components should not be coupled to `ui-widgets`.

**Comment by ismay** [comment]
> > Ok. That seems very specific to me. Covering just the app seems like a useful component to me (since that's coupled to the headerbar height, which is difficult to know in an app).
> 
> We only know the Headerbar height in `ui-widgets` though, and `ui-core` components should not be coupled to `ui-widgets`.

True.

**Comment by varl** [comment]
I am also not convinced that we need to expose this component, which is why it was deferred from 4.0.

@Mohammer5, you mentioned that he has a use case for it in MARy. Could you explain that use case so we can look at if it's a common one?

**Comment by varl** [comment]
This also doesn't actually **cover** anything since it doesn't have a Backdrop, so "AppCover" is not exactly right either. 🤔

**Comment by Mohammer5** [comment]
I want to use it to center the loading spinner and error message in the new maintenance app.

But I don't think we should prevent the user from using the header bar (why should we stop the user from navigating to another app while (possibly slowly) loading the initial data; e. g. when the user accidentally clicked the maintenance app icon)

**Comment by ismay** [comment]
> I want to use it to center the loading spinner and error message in the new maintenance app.
> 
> But I don't think we should prevent the user from using the header bar (why should we stop the user from navigating to another app while (possibly slowly) loading the initial data; e. g. when the user accidentally clicked the maintenance app icon)

I see. Maybe in that case it'd make sense to make the headerbar always be on top of the 'cover' components. Since it would be inconvenient to block the user from navigating to another app if it's stuck at a loading spinner. That would allow us to take care of this from within ui-core without coupling to ui-widgets. Without adding extra components.

**Comment by Mohammer5** [comment]
I think we can close this for now (and re-open if we see the necessity). I'll create a component in the new maintenance app

**Pull request closed without merging**
