### PR TITLE
chore: upgrade d2-style, reformat, and remove travis

### PR DESCRIPTION
**Pull request by varl**

### CODE REVIEW

**Comment by varl** [comment]
The Travis check is not going to pass, so I will have to force merge this after approval.

**Comment by varl** [comment]
Most, if not all, of the code changes should be due to the automatic sorting of propTypes.

**Comment by Mohammer5** [comment]
> The Travis check is not going to pass

@varl Can you explain this? Why should we merge a change that makes the build fail?

**Comment by varl** [comment]
> 
> 
> > The Travis check is not going to pass
> 
> @varl Can you explain this? Why should we merge a change that makes the build fail?

Because I deleted the `.travis.yml` file. The Travis checks are replaced by GitHub Actions checks.

**Comment by Mohammer5** [comment]
All good then, just wondering: why is travis checking this PR then?

**Comment by varl** [comment]
@Mohammer5 it's configured as a required check in GitHub, so GitHub sends the webhook to Travis, but Travis cannot find the config file, so it just stalls.

**Pull request merged**
