### PR TITLE
fix(chip remove icon): fix position cross browser

### LINKED ISSUE #418: Removeable chip icon placement
The 'remove' icon placement is not vertically centered in Firefox. Ideally needs to move down a pixel (maybe two). The centering is better in Chrome. 

Firefox screengrab:
image

### PR DESCRIPTION
**Pull request by Mohammer5**
Fixes #418 

I couldn't test this through browserstack in Edge, for some reason it doesn't load any of my local stories.
Could some one else please confirm that this works in Edge?

### CODE REVIEW

**Comment by varl** [comment]
I can test Edge tonight.

**Comment by varl** [comment]
So, a bit of bad news. The entire Storybook is broken in Edge for me:

Microsoft Edge 44.18980.1.0
Microsoft EdgeHTML 18.18980

image

>SCRIPT1028: SCRIPT1028: Expected identifier, string or number

```
{...prop_types_default.a,...customPropTypes}},,
```

**Comment by Mohammer5** [comment]
Seems to be an issue with the next branch in general..

**Comment by Mohammer5** [comment]
I think for now, this will fix the FF version and keeps the Chrome version intact.
Are you ok with me merging this one and if it turns out it doesn't display correctly on Edge, I'll fix it separately? @varl

**Pull request merged**
